apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-mwe
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:1.25.4-alpine-slim
      ports:
        - containerPort: 80
          hostIP: 0.0.0.0
          hostPort: 80